# Generated by Django 3.0.6 on 2020-08-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200718_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Not_civil_servant',
        ),
        migrations.AddField(
            model_name='civil_servant',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
